[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  # This tells Netlify to use esbuild to bundle dependencies from package.json
  node_bundler = "esbuild"
  external_node_modules = ["web-push"]
